### ISSUE TITLE
Compile error using Android NDK

### ISSUE THREAD

**Issue by tisch1981** [halsafar/libtmx-parser#6]
I'm getting a compile error when trying to compile libtmxparser using the android ndk.

The compile output is as follows:
[armeabi-v7a] Compile++ thumb: GameRenderer <= tinyxml2.cpp
[armeabi-v7a] Compile++ thumb: GameRenderer <= tmxparser.cpp
jni/libtmx-parser/src/tmxparser.cpp: In function 'tmxparser::TmxReturn tmxparser::_parseMapNode(tinyxml2::XMLElement*, tmxparser::TmxMap*)':
jni/libtmx-parser/src/tmxparser.cpp:217:2: error: expected ';' before 'return'
jni/libtmx-parser/src/tmxparser.cpp:218:2: error: expected ';' before 'return'
jni/libtmx-parser/src/tmxparser.cpp:219:2: error: expected ';' before 'return'
jni/libtmx-parser/src/tmxparser.cpp:220:2: error: expected ';' before 'return'
jni/libtmx-parser/src/tmxparser.cpp: In function 'tmxparser::TmxReturn tmxparser::_parseImageNode(tinyxml2::XMLElement*, tmxparser::TmxImage*)':
jni/libtmx-parser/src/tmxparser.cpp:305:2: error: expected ';' before 'return'
jni/libtmx-parser/src/tmxparser.cpp: In function 'tmxparser::TmxReturn tmxparser::_parseTilesetNode(tinyxml2::XMLElement*, tmxparser::TmxTileset*)':
jni/libtmx-parser/src/tmxparser.cpp:321:3: error: expected ';' before 'return'
jni/libtmx-parser/src/tmxparser.cpp:323:3: error: expected ';' before 'return'
jni/libtmx-parser/src/tmxparser.cpp:324:3: error: expected ';' before 'return'
make: *** [obj/local/armeabi-v7a/objs-debug/GameRenderer/libtmx-parser/src/tmxparser.o] Error 1

Process finished with exit code 2

Compile using NDK 10c and 10d results in the same output.

My Android.mk looks as follows:

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE    := GameRenderer
LOCAL_SRC_FILES := libtmx-parser/libs/tinyxml2/tinyxml2.cpp libtmx-parser/src/tmxparser.cpp
LOCAL_C_INCLUDES := $(LOCAL_PATH)/libtmx-parser/libs/tinyxml2
LOCAL_LDLIBS := -L$(SYSROOT)/usr/lib -llog -lGLESv2 -lOpenSLES
LOCAL_CPPFLAGS := -DANDROID -frtti -fexceptions -Wno-error=format-security -std=c++11
include $(BUILD_SHARED_LIBRARY)

 I'm using version 3b98e1ffbc07c727a821bcdebae875046d5febd3 on branch master of libtmx-parser.

Any ideas on what might be the problem?

**Comment by halsafar** [comment]
I will look into this in a few hours.  I will attempt to compile it the same as you and see if I can resolve the issue.  I currently do have it compiling for Android via the NDK but using the standalone compiler not the ndk-build scripts.

**Comment by halsafar** [comment]
Honestly it looks like it might have been as simple as a missing semicolon (embarrassing).  Pull into the update, it is only 1 revision past where you are working so the only change is the fixed semicolon.

**Comment by tisch1981** [comment]
Thanks, that fixed the compile issue!
